/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type QualityCode = 360 | 480 | 720 | 1080 | 1440 | 2160;

export const QualityCode = {
    NUMBER_360: 360 as QualityCode,
    NUMBER_480: 480 as QualityCode,
    NUMBER_720: 720 as QualityCode,
    NUMBER_1080: 1080 as QualityCode,
    NUMBER_1440: 1440 as QualityCode,
    NUMBER_2160: 2160 as QualityCode
};