/**
 * Swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { QualityCode } from '../model/qualityCode';
import { VideoBlockListVMRxjsResponse } from '../model/videoBlockListVMRxjsResponse';
import { VideoSearchConditionVM } from '../model/videoSearchConditionVM';
import { VideoVMListRxjsResponse } from '../model/videoVMListRxjsResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class VideoService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param vID
     * @param q
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiVideoGetBlockListGet(vID?: string, q?: QualityCode, observe?: 'body', reportProgress?: boolean): Observable<VideoBlockListVMRxjsResponse>;
    public apiVideoGetBlockListGet(vID?: string, q?: QualityCode, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<VideoBlockListVMRxjsResponse>>;
    public apiVideoGetBlockListGet(vID?: string, q?: QualityCode, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<VideoBlockListVMRxjsResponse>>;
    public apiVideoGetBlockListGet(vID?: string, q?: QualityCode, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (vID !== undefined && vID !== null) {
            queryParameters = queryParameters.set('vID', <any>vID);
        }
        if (q !== undefined && q !== null) {
            queryParameters = queryParameters.set('q', <any>q);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<VideoBlockListVMRxjsResponse>('get',`${this.basePath}/api/Video/GetBlockList`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param vID
     * @param q
     * @param s
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiVideoGetVideoGet(vID?: string, q?: QualityCode, s?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiVideoGetVideoGet(vID?: string, q?: QualityCode, s?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiVideoGetVideoGet(vID?: string, q?: QualityCode, s?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiVideoGetVideoGet(vID?: string, q?: QualityCode, s?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (vID !== undefined && vID !== null) {
            queryParameters = queryParameters.set('vID', <any>vID);
        }
        if (q !== undefined && q !== null) {
            queryParameters = queryParameters.set('q', <any>q);
        }
        if (s !== undefined && s !== null) {
            queryParameters = queryParameters.set('s', <any>s);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/Video/GetVideo`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiVideoSampleVideoStreamGet(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiVideoSampleVideoStreamGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiVideoSampleVideoStreamGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiVideoSampleVideoStreamGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/Video/SampleVideoStream`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress,
                responseType: 'blob' as 'json'
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param key
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiVideoSearchEncryptListPost(body?: VideoSearchConditionVM, key?: string, observe?: 'body', reportProgress?: boolean): Observable<VideoVMListRxjsResponse>;
    public apiVideoSearchEncryptListPost(body?: VideoSearchConditionVM, key?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<VideoVMListRxjsResponse>>;
    public apiVideoSearchEncryptListPost(body?: VideoSearchConditionVM, key?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<VideoVMListRxjsResponse>>;
    public apiVideoSearchEncryptListPost(body?: VideoSearchConditionVM, key?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (key !== undefined && key !== null) {
            queryParameters = queryParameters.set('key', <any>key);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<VideoVMListRxjsResponse>('post',`${this.basePath}/api/Video/SearchEncryptList`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
